//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string SoHD { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaSV { get; set; }
        public string MaPhong { get; set; }
        public Nullable<int> ThoiGianO { get; set; }
    }
}
