//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGHIDIENNUOC
    {
        public string MaPhieuGhiDienNuoc { get; set; }
        public string MaSo { get; set; }
        public string MaPhong { get; set; }
        public int SoDienNuoc { get; set; }
        public System.DateTime NgayGhi { get; set; }
        public bool LoaiPhieuGhi { get; set; }
    }
}
