//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public string MaPhong { get; set; }
        public string TenP { get; set; }
        public string ViTriP { get; set; }
        public int SoNguoiO { get; set; }
        public int SoNguoiTD { get; set; }
    }
}
