//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public int SoCMND { get; set; }
        public string SoDT { get; set; }
        public string DiaChi { get; set; }
    }
}
